server:
  port: 8761

spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: server-manager-service

eureka:
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost